node {
    stage ("Checkout DataService"){
        git branch: 'main', url: 'https://github.com/foilmirror/team6DataService'
    }
    
    stage ("Gradle Build - DataService") {
        dir('mcc-data-service') {
        	sh 'gradle clean build'
        }
    }
    
    stage ("Gradle Bootjar-Package - DataService") {
        dir('mcc-data-service') {
        	sh 'gradle bootjar'
        }
    }
    
    stage ("Containerize the app-docker build - DataService") {
        sh 'docker build --rm -t event-data:v1.0 .'
    }
    
    stage ("Inspect the docker image - DataService"){
        sh "docker images event-data:v1.0"
        sh "docker inspect event-data:v1.0"
    }
    
    stage ("Run Docker container instance - DataService"){
        sh "docker run -d --rm --name event-data -p 8080:8080 event-data:v1.0"
     }
    
    stage('User Acceptance Test - DataService') {
	
	  def response= input message: 'Is this build good to go?',
	   parameters: [choice(choices: 'Yes\nNo', 
	   description: '', name: 'Pass')]
	
	  if(response=="Yes") {
	    stage('Release - DataService') {
		    dir('mcc-data-service') {
		      sh 'gradle build -x test'
		      sh 'echo Release this version'
	      	}
	    }
	  }
    }
    
    stage("Production Deployment View"){
        sh "kubectl get deployments"
        sh "kubectl get pods"
        sh "kubectl get services"
    }
}