node {
    stage ("Checkout DataService"){
        git branch: 'main', url: 'https://github.com/foilmirror/team6dataservice_day2'
    }
    
    stage ("Gradle Build - DataService") {
        dir('mcc-data-service') {
        	sh 'gradle clean build'
        }
    }
    
    stage ("Gradle Bootjar-Package - DataService") {
        dir('mcc-data-service') {
        	sh 'gradle bootjar'
        }
    }
    
    stage('User Acceptance Test - DataService') {
	
	  def response= input message: 'Is this build good to go?',
	   parameters: [choice(choices: 'Yes\nNo', 
	   description: '', name: 'Pass')]
	
	  if(response=="Yes") {
	    stage('Release - DataService') {
		    dir('mcc-data-service') {
		      sh 'gradle build -x test'
		      sh 'echo Release this version'
	      	}
	    }
	  }
    }
}